Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: code.listener.DepartamentDetailsFunction
      CodeUri: C:\Users\AlumnoFP\IdeaProjects\Diego\A.D\RepasoEv2Ej3
      Runtime: java17
      Architectures:
        - x86_64